<?php
include('../adm/Conexao.php');
?>

<!-- SIDEBAR -->
<section id="sidebar">
	<ul class="side-menu top">
		<br><br>

		<li class="active">
			<a href="./nav-restrita.php">
				<i class='bx bxs-dashboard' ></i>
				<span class="text">Dashboard</span>
			</a>
		</li>
	
<li >			<a href="form-postagem.php">
				<i class='bx bxs-group' ></i>
				<span class="text">Postagem</span> <!--FORMULÁRIO DE POSTAGEM -->
			</a>
		</li>

		
<li >
	<a href="../restrito/feed2.php">
				<i class='bx bxs-group' ></i>
				<span class="text">Feed</span> <!--Feed-->
			</a>
		</li>
<li >		<a href="../restrito/pesquisa2.php">
				<i class='bx bxs-group' ></i>
				<span class="text">Encontre</span> <!--Feed-->
			</a>
		</li>

	</ul>
	
	<ul class="side-menu">
		
		<li >
			<a href="../restrito/porfile2.php">
				<i class='bx bxs-group' ></i>
				<span class="text">Perfil</span> <!--Perfil-->
			</a>
		</li>
		<li >
			<a href="logout.php" class="logout">
				<i class='bx bxs-log-out-circle' ></i>
				<span class="text">Sair</span>
			</a>
		</li>
	</ul>
</section>
<!-- SIDEBAR -->






